spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=UTC&rewriteBatchedStatements=TRUE
    username: ll
    password: 1

#    # 配置 DataSource Driver
#    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    #    # 指定 YAML 配置文件
#    url: jdbc:shardingsphere:classpath:sharding.yaml

  #  cache:
  #    redis:
  #      time-to-live: 1800000 # 设置缓存过期时间
  #  data:
  #    redis:
  #      host: 192.168.38.129
  #      database: 0
  #      port: 6379
  main:
    banner-mode: off # 关闭SpringBoot启动图标(banner)
    allow-bean-definition-overriding: true # 允许bean定义覆盖，后定义的覆盖先定义的
  application:
    name: reggie

# 开启mp的日志（输出到控制台）
mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出sql语句
  global-config:
    banner: off # 关闭mybatis plus启动图标
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-not-delete-value: 0 # 未删除为0
      logic-delete-value: 1 # 删除后为1
server:
  port: 8080
reggie:
  path: D:\CODE\JAVA\reggie\img\